DROP DATABASE BLOGDW1;

CREATE DATABASE BLOGDW1;

CREATE TABLE USUARIO (ID INT NOT NULL AUTO_INCREMENT, NOME VARCHAR(64) NOT NULL, SOBRENOME VARCHAR(64) NOT NULL, TELEFONE VARCHAR(11) NOT NULL, LOGIN VARCHAR(64) NOT NULL, SENHA VARCHAR(64) NOT NULL, ADMIN BOOLEAN DEFAULT FALSE, DELETADO BOOLEAN DEFAULT FALSE, PRIMARY KEY (ID));

CREATE TABLE POSTAGEM (ID INT NOT NULL AUTO_INCREMENT,TITULO VARCHAR(64) NOT NULL, TEXTO LONGTEXT, AUTOR INT NOT NULL, DATA DATETIME DEFAULT CURRENT_TIMESTAMP, DELETADO BOOLEAN DEFAULT FALSE, PRIMARY KEY (ID), FOREIGN KEY (AUTOR) REFERENCES USUARIO(ID));

CREATE TABLE COMENTARIO (ID INT NOT NULL AUTO_INCREMENT, AUTOR INT NOT NULL, TEXTO LONGTEXT NOT NULL, DATA DATETIME DEFAULT CURRENT_TIMESTAMP, IDPOSTAGEM INT NOT NULL, DELETADO BOOLEAN DEFAULT FALSE, PRIMARY KEY(ID), FOREIGN KEY (AUTOR) REFERENCES USUARIO(ID), FOREIGN KEY (IDPOSTAGEM) REFERENCES POSTAGEM(ID));

CREATE TABLE EVENTO (ID INT NOT NULL AUTO_INCREMENT ,NOME VARCHAR(60) NOT NULL, DESCRICAO VARCHAR(200) NOT NULL, ADDRESS VARCHAR(200) NOT NULL, DATA DATETIME DEFAULT CURRENT_TIMESTAMP, DELETADO BOOLEAN DEFAULT FALSE, PRIMARY KEY (ID));

CREATE TABLE PRESENCAEVENTO (IDUSUARIO INT NOT NULL, IDEVENTO INT NOT NULL, PRIMARY KEY(IDEVENTO), FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID), FOREIGN KEY (IDEVENTO) REFERENCES EVENTO(ID));
 
INSERT INTO USUARIO (NOME, SOBRENOME, TELEFONE, LOGIN, SENHA, ADMIN) VALUES ('ERINALDO', 'PEREIRA', '9999-9999', 'admin', 'admin', TRUE);

INSERT INTO USUARIO (NOME, SOBRENOME, TELEFONE, LOGIN, SENHA) VALUES ('ERINALDO', 'PEREIRA', '9999-9999', 'ERINALDO', 'PEREIRA');

INSERT INTO EVENTO (NOME, DESCRICAO, ADDRESS, DATA) VALUES ('Visita ao IFSP - São Carlos', 'Vamos levar a palavra de Deus aos alunos do IFSP, venha fazer parte dessa incrivel jornada!', 'Estrada Municipal Paulo Eduardo de A. Prado, São Carlos-SP, 13560-010, Brasil', '2018-12-10 21:00:00');

INSERT INTO EVENTO (NOME, DESCRICAO, ADDRESS, DATA) VALUES ('Visita ao Monte', 'Vamos iniciar mais um ano com uma corrente de orações. Não fique de fora deste glorioso momento!', 'Estrada Sca-472, 2398, São Carlos-SP, 13560-010, Brasil', '2018-12-31 23:59:00');

INSERT INTO POSTAGEM (TITULO, TEXTO, AUTOR) VALUES ('Neque porro quisquam est qui dolorem ipsum quia dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada nisi et mattis eleifend. Nullam accumsan enim ac lorem posuere pellentesque. Quisque rhoncus magna vitae turpis vulputate tincidunt. Aliquam iaculis tincidunt nisl, id convallis purus. Suspendisse accumsan felis justo, eget imperdiet nulla commodo sed. Curabitur urna massa, consectetur vel nisl sed, porta laoreet magna. Donec diam justo, vulputate vel commodo eu, gravida id odio. Proin non lorem ullamcorper, facilisis mi et, porttitor dui. Morbi et mauris a mauris congue mattis. Nunc porttitor arcu odio, vel cursus elit placerat eget. Vivamus vel urna non quam pharetra pulvinar.

Morbi mattis enim a consectetur laoreet. Mauris tempor eu nulla ut rutrum. Nulla at eros nisl. Nunc lobortis orci libero, sed maximus massa consequat ut. Aliquam feugiat, leo in malesuada ultricies, sem mauris ultricies neque, eget semper nibh ipsum quis orci. Proin sed dui et libero tempor bibendum in eget ex. Nam quis tellus bibendum, molestie sapien ut, pharetra nisl. Nunc augue erat, commodo ut bibendum non, convallis porta nisl. Suspendisse sit amet consectetur tellus, ac dapibus nulla. Ut posuere tristique lectus, vitae semper orci accumsan ac. Mauris est ex, egestas eget enim et, egestas tincidunt tortor. Quisque mattis aliquam risus, sed viverra urna consectetur non. Donec blandit ligula fringilla commodo auctor. Praesent vulputate, dolor ac blandit hendrerit, mauris ligula condimentum mi, a dignissim est ex ac nisi. Etiam tempus vel metus vitae ultricies.

Ut luctus neque lectus, in molestie urna euismod eu. Pellentesque sed varius odio. Nullam non sodales mi. Phasellus at sapien ipsum. In aliquam pulvinar est porta porttitor. Maecenas vel eros tellus. Vestibulum tincidunt volutpat nibh, at fringilla libero scelerisque in.

Phasellus maximus erat ac nisi fermentum imperdiet. Aenean in metus ut erat cursus tincidunt. Nam lacinia est quis porttitor interdum. Vivamus interdum enim pretium enim porta, quis varius velit ultrices. Donec commodo enim vel risus ultricies interdum. Ut dapibus pharetra semper. Vivamus sed faucibus felis, non iaculis quam. Ut sed tellus eu augue pulvinar convallis. Aliquam tincidunt leo non accumsan consequat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec eget gravida turpis. Integer placerat ipsum mi, id venenatis velit ultricies eu. Mauris sit amet egestas nunc, vel vestibulum turpis. Donec eu imperdiet felis, in pretium ligula. Morbi nibh quam, convallis a ante sit amet, rhoncus fermentum odio.

Phasellus gravida sit amet massa ac congue. Morbi porta augue in nunc tincidunt dictum. Curabitur aliquam sem nec odio laoreet aliquam. Nullam arcu nibh, mollis ac ipsum ut, sodales tempus risus. Curabitur aliquam, purus a elementum lobortis, nisl ante lacinia felis, non congue justo lectus sed velit. In eu neque finibus, sodales neque vitae, ornare massa. Duis ut tincidunt nisl. Sed eros ligula, eleifend a vulputate id, hendrerit sed libero. Fusce at dui sapien. Suspendisse at enim tincidunt, venenatis libero at, hendrerit augue. Donec tempor augue eu leo efficitur tempus. Aliquam erat volutpat.

Vestibulum in venenatis ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque bibendum auctor euismod. Morbi vulputate tempus dictum. Vestibulum eu.', 1);


INSERT INTO POSTAGEM (TITULO, TEXTO, AUTOR) VALUES ('Neque porro quisquam est qui dolorem ipsum quia dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada nisi et mattis eleifend. Nullam accumsan enim ac lorem posuere pellentesque. Quisque rhoncus magna vitae turpis vulputate tincidunt. Aliquam iaculis tincidunt nisl, id convallis purus. Suspendisse accumsan felis justo, eget imperdiet nulla commodo sed. Curabitur urna massa, consectetur vel nisl sed, porta laoreet magna. Donec diam justo, vulputate vel commodo eu, gravida id odio. Proin non lorem ullamcorper, facilisis mi et, porttitor dui. Morbi et mauris a mauris congue mattis. Nunc porttitor arcu odio, vel cursus elit placerat eget. Vivamus vel urna non quam pharetra pulvinar.

Morbi mattis enim a consectetur laoreet. Mauris tempor eu nulla ut rutrum. Nulla at eros nisl. Nunc lobortis orci libero, sed maximus massa consequat ut. Aliquam feugiat, leo in malesuada ultricies, sem mauris ultricies neque, eget semper nibh ipsum quis orci. Proin sed dui et libero tempor bibendum in eget ex. Nam quis tellus bibendum, molestie sapien ut, pharetra nisl. Nunc augue erat, commodo ut bibendum non, convallis porta nisl. Suspendisse sit amet consectetur tellus, ac dapibus nulla. Ut posuere tristique lectus, vitae semper orci accumsan ac. Mauris est ex, egestas eget enim et, egestas tincidunt tortor. Quisque mattis aliquam risus, sed viverra urna consectetur non. Donec blandit ligula fringilla commodo auctor. Praesent vulputate, dolor ac blandit hendrerit, mauris ligula condimentum mi, a dignissim est ex ac nisi. Etiam tempus vel metus vitae ultricies.

Ut luctus neque lectus, in molestie urna euismod eu. Pellentesque sed varius odio. Nullam non sodales mi. Phasellus at sapien ipsum. In aliquam pulvinar est porta porttitor. Maecenas vel eros tellus. Vestibulum tincidunt volutpat nibh, at fringilla libero scelerisque in.

Phasellus maximus erat ac nisi fermentum imperdiet. Aenean in metus ut erat cursus tincidunt. Nam lacinia est quis porttitor interdum. Vivamus interdum enim pretium enim porta, quis varius velit ultrices. Donec commodo enim vel risus ultricies interdum. Ut dapibus pharetra semper. Vivamus sed faucibus felis, non iaculis quam. Ut sed tellus eu augue pulvinar convallis. Aliquam tincidunt leo non accumsan consequat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec eget gravida turpis. Integer placerat ipsum mi, id venenatis velit ultricies eu. Mauris sit amet egestas nunc, vel vestibulum turpis. Donec eu imperdiet felis, in pretium ligula. Morbi nibh quam, convallis a ante sit amet, rhoncus fermentum odio.

Phasellus gravida sit amet massa ac congue. Morbi porta augue in nunc tincidunt dictum. Curabitur aliquam sem nec odio laoreet aliquam. Nullam arcu nibh, mollis ac ipsum ut, sodales tempus risus. Curabitur aliquam, purus a elementum lobortis, nisl ante lacinia felis, non congue justo lectus sed velit. In eu neque finibus, sodales neque vitae, ornare massa. Duis ut tincidunt nisl. Sed eros ligula, eleifend a vulputate id, hendrerit sed libero. Fusce at dui sapien. Suspendisse at enim tincidunt, venenatis libero at, hendrerit augue. Donec tempor augue eu leo efficitur tempus. Aliquam erat volutpat.

Vestibulum in venenatis ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque bibendum auctor euismod. Morbi vulputate tempus dictum. Vestibulum eu.', 1);


INSERT INTO POSTAGEM (TITULO, TEXTO, AUTOR) VALUES ('Neque porro quisquam est qui dolorem ipsum quia dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada nisi et mattis eleifend. Nullam accumsan enim ac lorem posuere pellentesque. Quisque rhoncus magna vitae turpis vulputate tincidunt. Aliquam iaculis tincidunt nisl, id convallis purus. Suspendisse accumsan felis justo, eget imperdiet nulla commodo sed. Curabitur urna massa, consectetur vel nisl sed, porta laoreet magna. Donec diam justo, vulputate vel commodo eu, gravida id odio. Proin non lorem ullamcorper, facilisis mi et, porttitor dui. Morbi et mauris a mauris congue mattis. Nunc porttitor arcu odio, vel cursus elit placerat eget. Vivamus vel urna non quam pharetra pulvinar.

Morbi mattis enim a consectetur laoreet. Mauris tempor eu nulla ut rutrum. Nulla at eros nisl. Nunc lobortis orci libero, sed maximus massa consequat ut. Aliquam feugiat, leo in malesuada ultricies, sem mauris ultricies neque, eget semper nibh ipsum quis orci. Proin sed dui et libero tempor bibendum in eget ex. Nam quis tellus bibendum, molestie sapien ut, pharetra nisl. Nunc augue erat, commodo ut bibendum non, convallis porta nisl. Suspendisse sit amet consectetur tellus, ac dapibus nulla. Ut posuere tristique lectus, vitae semper orci accumsan ac. Mauris est ex, egestas eget enim et, egestas tincidunt tortor. Quisque mattis aliquam risus, sed viverra urna consectetur non. Donec blandit ligula fringilla commodo auctor. Praesent vulputate, dolor ac blandit hendrerit, mauris ligula condimentum mi, a dignissim est ex ac nisi. Etiam tempus vel metus vitae ultricies.

Ut luctus neque lectus, in molestie urna euismod eu. Pellentesque sed varius odio. Nullam non sodales mi. Phasellus at sapien ipsum. In aliquam pulvinar est porta porttitor. Maecenas vel eros tellus. Vestibulum tincidunt volutpat nibh, at fringilla libero scelerisque in.

Phasellus maximus erat ac nisi fermentum imperdiet. Aenean in metus ut erat cursus tincidunt. Nam lacinia est quis porttitor interdum. Vivamus interdum enim pretium enim porta, quis varius velit ultrices. Donec commodo enim vel risus ultricies interdum. Ut dapibus pharetra semper. Vivamus sed faucibus felis, non iaculis quam. Ut sed tellus eu augue pulvinar convallis. Aliquam tincidunt leo non accumsan consequat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec eget gravida turpis. Integer placerat ipsum mi, id venenatis velit ultricies eu. Mauris sit amet egestas nunc, vel vestibulum turpis. Donec eu imperdiet felis, in pretium ligula. Morbi nibh quam, convallis a ante sit amet, rhoncus fermentum odio.

Phasellus gravida sit amet massa ac congue. Morbi porta augue in nunc tincidunt dictum. Curabitur aliquam sem nec odio laoreet aliquam. Nullam arcu nibh, mollis ac ipsum ut, sodales tempus risus. Curabitur aliquam, purus a elementum lobortis, nisl ante lacinia felis, non congue justo lectus sed velit. In eu neque finibus, sodales neque vitae, ornare massa. Duis ut tincidunt nisl. Sed eros ligula, eleifend a vulputate id, hendrerit sed libero. Fusce at dui sapien. Suspendisse at enim tincidunt, venenatis libero at, hendrerit augue. Donec tempor augue eu leo efficitur tempus. Aliquam erat volutpat.

Vestibulum in venenatis ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque bibendum auctor euismod. Morbi vulputate tempus dictum. Vestibulum eu.', 1);


INSERT INTO POSTAGEM (TITULO, TEXTO, AUTOR) VALUES ('Neque porro quisquam est qui dolorem ipsum quia dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada nisi et mattis eleifend. Nullam accumsan enim ac lorem posuere pellentesque. Quisque rhoncus magna vitae turpis vulputate tincidunt. Aliquam iaculis tincidunt nisl, id convallis purus. Suspendisse accumsan felis justo, eget imperdiet nulla commodo sed. Curabitur urna massa, consectetur vel nisl sed, porta laoreet magna. Donec diam justo, vulputate vel commodo eu, gravida id odio. Proin non lorem ullamcorper, facilisis mi et, porttitor dui. Morbi et mauris a mauris congue mattis. Nunc porttitor arcu odio, vel cursus elit placerat eget. Vivamus vel urna non quam pharetra pulvinar.

Morbi mattis enim a consectetur laoreet. Mauris tempor eu nulla ut rutrum. Nulla at eros nisl. Nunc lobortis orci libero, sed maximus massa consequat ut. Aliquam feugiat, leo in malesuada ultricies, sem mauris ultricies neque, eget semper nibh ipsum quis orci. Proin sed dui et libero tempor bibendum in eget ex. Nam quis tellus bibendum, molestie sapien ut, pharetra nisl. Nunc augue erat, commodo ut bibendum non, convallis porta nisl. Suspendisse sit amet consectetur tellus, ac dapibus nulla. Ut posuere tristique lectus, vitae semper orci accumsan ac. Mauris est ex, egestas eget enim et, egestas tincidunt tortor. Quisque mattis aliquam risus, sed viverra urna consectetur non. Donec blandit ligula fringilla commodo auctor. Praesent vulputate, dolor ac blandit hendrerit, mauris ligula condimentum mi, a dignissim est ex ac nisi. Etiam tempus vel metus vitae ultricies.

Ut luctus neque lectus, in molestie urna euismod eu. Pellentesque sed varius odio. Nullam non sodales mi. Phasellus at sapien ipsum. In aliquam pulvinar est porta porttitor. Maecenas vel eros tellus. Vestibulum tincidunt volutpat nibh, at fringilla libero scelerisque in.

Phasellus maximus erat ac nisi fermentum imperdiet. Aenean in metus ut erat cursus tincidunt. Nam lacinia est quis porttitor interdum. Vivamus interdum enim pretium enim porta, quis varius velit ultrices. Donec commodo enim vel risus ultricies interdum. Ut dapibus pharetra semper. Vivamus sed faucibus felis, non iaculis quam. Ut sed tellus eu augue pulvinar convallis. Aliquam tincidunt leo non accumsan consequat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec eget gravida turpis. Integer placerat ipsum mi, id venenatis velit ultricies eu. Mauris sit amet egestas nunc, vel vestibulum turpis. Donec eu imperdiet felis, in pretium ligula. Morbi nibh quam, convallis a ante sit amet, rhoncus fermentum odio.

Phasellus gravida sit amet massa ac congue. Morbi porta augue in nunc tincidunt dictum. Curabitur aliquam sem nec odio laoreet aliquam. Nullam arcu nibh, mollis ac ipsum ut, sodales tempus risus. Curabitur aliquam, purus a elementum lobortis, nisl ante lacinia felis, non congue justo lectus sed velit. In eu neque finibus, sodales neque vitae, ornare massa. Duis ut tincidunt nisl. Sed eros ligula, eleifend a vulputate id, hendrerit sed libero. Fusce at dui sapien. Suspendisse at enim tincidunt, venenatis libero at, hendrerit augue. Donec tempor augue eu leo efficitur tempus. Aliquam erat volutpat.

Vestibulum in venenatis ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque bibendum auctor euismod. Morbi vulputate tempus dictum. Vestibulum eu.', 1);


INSERT INTO POSTAGEM (TITULO, TEXTO, AUTOR) VALUES ('Neque porro quisquam est qui dolorem ipsum quia dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada nisi et mattis eleifend. Nullam accumsan enim ac lorem posuere pellentesque. Quisque rhoncus magna vitae turpis vulputate tincidunt. Aliquam iaculis tincidunt nisl, id convallis purus. Suspendisse accumsan felis justo, eget imperdiet nulla commodo sed. Curabitur urna massa, consectetur vel nisl sed, porta laoreet magna. Donec diam justo, vulputate vel commodo eu, gravida id odio. Proin non lorem ullamcorper, facilisis mi et, porttitor dui. Morbi et mauris a mauris congue mattis. Nunc porttitor arcu odio, vel cursus elit placerat eget. Vivamus vel urna non quam pharetra pulvinar.

Morbi mattis enim a consectetur laoreet. Mauris tempor eu nulla ut rutrum. Nulla at eros nisl. Nunc lobortis orci libero, sed maximus massa consequat ut. Aliquam feugiat, leo in malesuada ultricies, sem mauris ultricies neque, eget semper nibh ipsum quis orci. Proin sed dui et libero tempor bibendum in eget ex. Nam quis tellus bibendum, molestie sapien ut, pharetra nisl. Nunc augue erat, commodo ut bibendum non, convallis porta nisl. Suspendisse sit amet consectetur tellus, ac dapibus nulla. Ut posuere tristique lectus, vitae semper orci accumsan ac. Mauris est ex, egestas eget enim et, egestas tincidunt tortor. Quisque mattis aliquam risus, sed viverra urna consectetur non. Donec blandit ligula fringilla commodo auctor. Praesent vulputate, dolor ac blandit hendrerit, mauris ligula condimentum mi, a dignissim est ex ac nisi. Etiam tempus vel metus vitae ultricies.

Ut luctus neque lectus, in molestie urna euismod eu. Pellentesque sed varius odio. Nullam non sodales mi. Phasellus at sapien ipsum. In aliquam pulvinar est porta porttitor. Maecenas vel eros tellus. Vestibulum tincidunt volutpat nibh, at fringilla libero scelerisque in.

Phasellus maximus erat ac nisi fermentum imperdiet. Aenean in metus ut erat cursus tincidunt. Nam lacinia est quis porttitor interdum. Vivamus interdum enim pretium enim porta, quis varius velit ultrices. Donec commodo enim vel risus ultricies interdum. Ut dapibus pharetra semper. Vivamus sed faucibus felis, non iaculis quam. Ut sed tellus eu augue pulvinar convallis. Aliquam tincidunt leo non accumsan consequat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec eget gravida turpis. Integer placerat ipsum mi, id venenatis velit ultricies eu. Mauris sit amet egestas nunc, vel vestibulum turpis. Donec eu imperdiet felis, in pretium ligula. Morbi nibh quam, convallis a ante sit amet, rhoncus fermentum odio.

Phasellus gravida sit amet massa ac congue. Morbi porta augue in nunc tincidunt dictum. Curabitur aliquam sem nec odio laoreet aliquam. Nullam arcu nibh, mollis ac ipsum ut, sodales tempus risus. Curabitur aliquam, purus a elementum lobortis, nisl ante lacinia felis, non congue justo lectus sed velit. In eu neque finibus, sodales neque vitae, ornare massa. Duis ut tincidunt nisl. Sed eros ligula, eleifend a vulputate id, hendrerit sed libero. Fusce at dui sapien. Suspendisse at enim tincidunt, venenatis libero at, hendrerit augue. Donec tempor augue eu leo efficitur tempus. Aliquam erat volutpat.

Vestibulum in venenatis ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque bibendum auctor euismod. Morbi vulputate tempus dictum. Vestibulum eu.', 1);


INSERT INTO POSTAGEM (TITULO, TEXTO, AUTOR) VALUES ('Neque porro quisquam est qui dolorem ipsum quia dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada nisi et mattis eleifend. Nullam accumsan enim ac lorem posuere pellentesque. Quisque rhoncus magna vitae turpis vulputate tincidunt. Aliquam iaculis tincidunt nisl, id convallis purus. Suspendisse accumsan felis justo, eget imperdiet nulla commodo sed. Curabitur urna massa, consectetur vel nisl sed, porta laoreet magna. Donec diam justo, vulputate vel commodo eu, gravida id odio. Proin non lorem ullamcorper, facilisis mi et, porttitor dui. Morbi et mauris a mauris congue mattis. Nunc porttitor arcu odio, vel cursus elit placerat eget. Vivamus vel urna non quam pharetra pulvinar.

Morbi mattis enim a consectetur laoreet. Mauris tempor eu nulla ut rutrum. Nulla at eros nisl. Nunc lobortis orci libero, sed maximus massa consequat ut. Aliquam feugiat, leo in malesuada ultricies, sem mauris ultricies neque, eget semper nibh ipsum quis orci. Proin sed dui et libero tempor bibendum in eget ex. Nam quis tellus bibendum, molestie sapien ut, pharetra nisl. Nunc augue erat, commodo ut bibendum non, convallis porta nisl. Suspendisse sit amet consectetur tellus, ac dapibus nulla. Ut posuere tristique lectus, vitae semper orci accumsan ac. Mauris est ex, egestas eget enim et, egestas tincidunt tortor. Quisque mattis aliquam risus, sed viverra urna consectetur non. Donec blandit ligula fringilla commodo auctor. Praesent vulputate, dolor ac blandit hendrerit, mauris ligula condimentum mi, a dignissim est ex ac nisi. Etiam tempus vel metus vitae ultricies.

Ut luctus neque lectus, in molestie urna euismod eu. Pellentesque sed varius odio. Nullam non sodales mi. Phasellus at sapien ipsum. In aliquam pulvinar est porta porttitor. Maecenas vel eros tellus. Vestibulum tincidunt volutpat nibh, at fringilla libero scelerisque in.

Phasellus maximus erat ac nisi fermentum imperdiet. Aenean in metus ut erat cursus tincidunt. Nam lacinia est quis porttitor interdum. Vivamus interdum enim pretium enim porta, quis varius velit ultrices. Donec commodo enim vel risus ultricies interdum. Ut dapibus pharetra semper. Vivamus sed faucibus felis, non iaculis quam. Ut sed tellus eu augue pulvinar convallis. Aliquam tincidunt leo non accumsan consequat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec eget gravida turpis. Integer placerat ipsum mi, id venenatis velit ultricies eu. Mauris sit amet egestas nunc, vel vestibulum turpis. Donec eu imperdiet felis, in pretium ligula. Morbi nibh quam, convallis a ante sit amet, rhoncus fermentum odio.

Phasellus gravida sit amet massa ac congue. Morbi porta augue in nunc tincidunt dictum. Curabitur aliquam sem nec odio laoreet aliquam. Nullam arcu nibh, mollis ac ipsum ut, sodales tempus risus. Curabitur aliquam, purus a elementum lobortis, nisl ante lacinia felis, non congue justo lectus sed velit. In eu neque finibus, sodales neque vitae, ornare massa. Duis ut tincidunt nisl. Sed eros ligula, eleifend a vulputate id, hendrerit sed libero. Fusce at dui sapien. Suspendisse at enim tincidunt, venenatis libero at, hendrerit augue. Donec tempor augue eu leo efficitur tempus. Aliquam erat volutpat.

Vestibulum in venenatis ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque bibendum auctor euismod. Morbi vulputate tempus dictum. Vestibulum eu.', 1);


INSERT INTO POSTAGEM (TITULO, TEXTO, AUTOR) VALUES ('Neque porro quisquam est qui dolorem ipsum quia dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada nisi et mattis eleifend. Nullam accumsan enim ac lorem posuere pellentesque. Quisque rhoncus magna vitae turpis vulputate tincidunt. Aliquam iaculis tincidunt nisl, id convallis purus. Suspendisse accumsan felis justo, eget imperdiet nulla commodo sed. Curabitur urna massa, consectetur vel nisl sed, porta laoreet magna. Donec diam justo, vulputate vel commodo eu, gravida id odio. Proin non lorem ullamcorper, facilisis mi et, porttitor dui. Morbi et mauris a mauris congue mattis. Nunc porttitor arcu odio, vel cursus elit placerat eget. Vivamus vel urna non quam pharetra pulvinar.

Morbi mattis enim a consectetur laoreet. Mauris tempor eu nulla ut rutrum. Nulla at eros nisl. Nunc lobortis orci libero, sed maximus massa consequat ut. Aliquam feugiat, leo in malesuada ultricies, sem mauris ultricies neque, eget semper nibh ipsum quis orci. Proin sed dui et libero tempor bibendum in eget ex. Nam quis tellus bibendum, molestie sapien ut, pharetra nisl. Nunc augue erat, commodo ut bibendum non, convallis porta nisl. Suspendisse sit amet consectetur tellus, ac dapibus nulla. Ut posuere tristique lectus, vitae semper orci accumsan ac. Mauris est ex, egestas eget enim et, egestas tincidunt tortor. Quisque mattis aliquam risus, sed viverra urna consectetur non. Donec blandit ligula fringilla commodo auctor. Praesent vulputate, dolor ac blandit hendrerit, mauris ligula condimentum mi, a dignissim est ex ac nisi. Etiam tempus vel metus vitae ultricies.

Ut luctus neque lectus, in molestie urna euismod eu. Pellentesque sed varius odio. Nullam non sodales mi. Phasellus at sapien ipsum. In aliquam pulvinar est porta porttitor. Maecenas vel eros tellus. Vestibulum tincidunt volutpat nibh, at fringilla libero scelerisque in.

Phasellus maximus erat ac nisi fermentum imperdiet. Aenean in metus ut erat cursus tincidunt. Nam lacinia est quis porttitor interdum. Vivamus interdum enim pretium enim porta, quis varius velit ultrices. Donec commodo enim vel risus ultricies interdum. Ut dapibus pharetra semper. Vivamus sed faucibus felis, non iaculis quam. Ut sed tellus eu augue pulvinar convallis. Aliquam tincidunt leo non accumsan consequat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec eget gravida turpis. Integer placerat ipsum mi, id venenatis velit ultricies eu. Mauris sit amet egestas nunc, vel vestibulum turpis. Donec eu imperdiet felis, in pretium ligula. Morbi nibh quam, convallis a ante sit amet, rhoncus fermentum odio.

Phasellus gravida sit amet massa ac congue. Morbi porta augue in nunc tincidunt dictum. Curabitur aliquam sem nec odio laoreet aliquam. Nullam arcu nibh, mollis ac ipsum ut, sodales tempus risus. Curabitur aliquam, purus a elementum lobortis, nisl ante lacinia felis, non congue justo lectus sed velit. In eu neque finibus, sodales neque vitae, ornare massa. Duis ut tincidunt nisl. Sed eros ligula, eleifend a vulputate id, hendrerit sed libero. Fusce at dui sapien. Suspendisse at enim tincidunt, venenatis libero at, hendrerit augue. Donec tempor augue eu leo efficitur tempus. Aliquam erat volutpat.

Vestibulum in venenatis ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque bibendum auctor euismod. Morbi vulputate tempus dictum. Vestibulum eu.', 1);


INSERT INTO POSTAGEM (TITULO, TEXTO, AUTOR) VALUES ('Neque porro quisquam est qui dolorem ipsum quia dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada nisi et mattis eleifend. Nullam accumsan enim ac lorem posuere pellentesque. Quisque rhoncus magna vitae turpis vulputate tincidunt. Aliquam iaculis tincidunt nisl, id convallis purus. Suspendisse accumsan felis justo, eget imperdiet nulla commodo sed. Curabitur urna massa, consectetur vel nisl sed, porta laoreet magna. Donec diam justo, vulputate vel commodo eu, gravida id odio. Proin non lorem ullamcorper, facilisis mi et, porttitor dui. Morbi et mauris a mauris congue mattis. Nunc porttitor arcu odio, vel cursus elit placerat eget. Vivamus vel urna non quam pharetra pulvinar.

Morbi mattis enim a consectetur laoreet. Mauris tempor eu nulla ut rutrum. Nulla at eros nisl. Nunc lobortis orci libero, sed maximus massa consequat ut. Aliquam feugiat, leo in malesuada ultricies, sem mauris ultricies neque, eget semper nibh ipsum quis orci. Proin sed dui et libero tempor bibendum in eget ex. Nam quis tellus bibendum, molestie sapien ut, pharetra nisl. Nunc augue erat, commodo ut bibendum non, convallis porta nisl. Suspendisse sit amet consectetur tellus, ac dapibus nulla. Ut posuere tristique lectus, vitae semper orci accumsan ac. Mauris est ex, egestas eget enim et, egestas tincidunt tortor. Quisque mattis aliquam risus, sed viverra urna consectetur non. Donec blandit ligula fringilla commodo auctor. Praesent vulputate, dolor ac blandit hendrerit, mauris ligula condimentum mi, a dignissim est ex ac nisi. Etiam tempus vel metus vitae ultricies.

Ut luctus neque lectus, in molestie urna euismod eu. Pellentesque sed varius odio. Nullam non sodales mi. Phasellus at sapien ipsum. In aliquam pulvinar est porta porttitor. Maecenas vel eros tellus. Vestibulum tincidunt volutpat nibh, at fringilla libero scelerisque in.

Phasellus maximus erat ac nisi fermentum imperdiet. Aenean in metus ut erat cursus tincidunt. Nam lacinia est quis porttitor interdum. Vivamus interdum enim pretium enim porta, quis varius velit ultrices. Donec commodo enim vel risus ultricies interdum. Ut dapibus pharetra semper. Vivamus sed faucibus felis, non iaculis quam. Ut sed tellus eu augue pulvinar convallis. Aliquam tincidunt leo non accumsan consequat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec eget gravida turpis. Integer placerat ipsum mi, id venenatis velit ultricies eu. Mauris sit amet egestas nunc, vel vestibulum turpis. Donec eu imperdiet felis, in pretium ligula. Morbi nibh quam, convallis a ante sit amet, rhoncus fermentum odio.

Phasellus gravida sit amet massa ac congue. Morbi porta augue in nunc tincidunt dictum. Curabitur aliquam sem nec odio laoreet aliquam. Nullam arcu nibh, mollis ac ipsum ut, sodales tempus risus. Curabitur aliquam, purus a elementum lobortis, nisl ante lacinia felis, non congue justo lectus sed velit. In eu neque finibus, sodales neque vitae, ornare massa. Duis ut tincidunt nisl. Sed eros ligula, eleifend a vulputate id, hendrerit sed libero. Fusce at dui sapien. Suspendisse at enim tincidunt, venenatis libero at, hendrerit augue. Donec tempor augue eu leo efficitur tempus. Aliquam erat volutpat.

Vestibulum in venenatis ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque bibendum auctor euismod. Morbi vulputate tempus dictum. Vestibulum eu.', 1);


INSERT INTO POSTAGEM (TITULO, TEXTO, AUTOR) VALUES ('Neque porro quisquam est qui dolorem ipsum quia dolor sit amet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada nisi et mattis eleifend. Nullam accumsan enim ac lorem posuere pellentesque. Quisque rhoncus magna vitae turpis vulputate tincidunt. Aliquam iaculis tincidunt nisl, id convallis purus. Suspendisse accumsan felis justo, eget imperdiet nulla commodo sed. Curabitur urna massa, consectetur vel nisl sed, porta laoreet magna. Donec diam justo, vulputate vel commodo eu, gravida id odio. Proin non lorem ullamcorper, facilisis mi et, porttitor dui. Morbi et mauris a mauris congue mattis. Nunc porttitor arcu odio, vel cursus elit placerat eget. Vivamus vel urna non quam pharetra pulvinar.

Morbi mattis enim a consectetur laoreet. Mauris tempor eu nulla ut rutrum. Nulla at eros nisl. Nunc lobortis orci libero, sed maximus massa consequat ut. Aliquam feugiat, leo in malesuada ultricies, sem mauris ultricies neque, eget semper nibh ipsum quis orci. Proin sed dui et libero tempor bibendum in eget ex. Nam quis tellus bibendum, molestie sapien ut, pharetra nisl. Nunc augue erat, commodo ut bibendum non, convallis porta nisl. Suspendisse sit amet consectetur tellus, ac dapibus nulla. Ut posuere tristique lectus, vitae semper orci accumsan ac. Mauris est ex, egestas eget enim et, egestas tincidunt tortor. Quisque mattis aliquam risus, sed viverra urna consectetur non. Donec blandit ligula fringilla commodo auctor. Praesent vulputate, dolor ac blandit hendrerit, mauris ligula condimentum mi, a dignissim est ex ac nisi. Etiam tempus vel metus vitae ultricies.

Ut luctus neque lectus, in molestie urna euismod eu. Pellentesque sed varius odio. Nullam non sodales mi. Phasellus at sapien ipsum. In aliquam pulvinar est porta porttitor. Maecenas vel eros tellus. Vestibulum tincidunt volutpat nibh, at fringilla libero scelerisque in.

Phasellus maximus erat ac nisi fermentum imperdiet. Aenean in metus ut erat cursus tincidunt. Nam lacinia est quis porttitor interdum. Vivamus interdum enim pretium enim porta, quis varius velit ultrices. Donec commodo enim vel risus ultricies interdum. Ut dapibus pharetra semper. Vivamus sed faucibus felis, non iaculis quam. Ut sed tellus eu augue pulvinar convallis. Aliquam tincidunt leo non accumsan consequat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec eget gravida turpis. Integer placerat ipsum mi, id venenatis velit ultricies eu. Mauris sit amet egestas nunc, vel vestibulum turpis. Donec eu imperdiet felis, in pretium ligula. Morbi nibh quam, convallis a ante sit amet, rhoncus fermentum odio.

Phasellus gravida sit amet massa ac congue. Morbi porta augue in nunc tincidunt dictum. Curabitur aliquam sem nec odio laoreet aliquam. Nullam arcu nibh, mollis ac ipsum ut, sodales tempus risus. Curabitur aliquam, purus a elementum lobortis, nisl ante lacinia felis, non congue justo lectus sed velit. In eu neque finibus, sodales neque vitae, ornare massa. Duis ut tincidunt nisl. Sed eros ligula, eleifend a vulputate id, hendrerit sed libero. Fusce at dui sapien. Suspendisse at enim tincidunt, venenatis libero at, hendrerit augue. Donec tempor augue eu leo efficitur tempus. Aliquam erat volutpat.

Vestibulum in venenatis ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque bibendum auctor euismod. Morbi vulputate tempus dictum. Vestibulum eu.', 1);


INSERT INTO COMENTARIO (AUTOR, TEXTO, IDPOSTAGEM) VALUES (1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae', 1);
INSERT INTO COMENTARIO (AUTOR, TEXTO, IDPOSTAGEM) VALUES (1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae', 1);
INSERT INTO COMENTARIO (AUTOR, TEXTO, IDPOSTAGEM) VALUES (1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae', 1);
INSERT INTO COMENTARIO (AUTOR, TEXTO, IDPOSTAGEM) VALUES (1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae', 1);
INSERT INTO COMENTARIO (AUTOR, TEXTO, IDPOSTAGEM) VALUES (1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae', 1);
INSERT INTO COMENTARIO (AUTOR, TEXTO, IDPOSTAGEM) VALUES (1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae', 1);
INSERT INTO COMENTARIO (AUTOR, TEXTO, IDPOSTAGEM) VALUES (1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae', 1);
